# Generated by Django 3.0.5 on 2020-04-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Client'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Company'),
        ),
    ]
